import hashlib
import re
import uuid
from collections import Counter
from dataclasses import dataclass
from datetime import UTC, datetime
from html import escape
from io import BytesIO
from pathlib import Path
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.core.config import get_settings
from app.models.asset import Asset
from app.models.audit_review_finding import AuditReviewFinding
from app.models.audit_review_job import AuditReviewJob
from app.models.audit_review_report import AuditReviewReport
from app.models.audit_review_score import AuditReviewScore
from app.services.audit_review_scoring_service import OVERALL_CHECK_CODE
from app.services.audit_review_service import AuditReviewNotFoundError, AuditReviewValidationError
from app.services.audit_review_workflow_metadata import (
    ACTOR_TYPE_SYSTEM,
    DEFAULT_SYSTEM_ACTOR,
    build_report_workflow_metadata,
    get_audit_review_workflow_config,
    update_final_pdf_metadata,
)


REPORT_TITLE = "Veeva Audit Trail Periodic Review Report"
APPLICATION_NAME = "ValidateNow / Compliance Manager"
CONFIDENTIALITY_LABEL = "Confidential / Controlled Document"
PDF_MEDIA_TYPE = "application/pdf"
PDF_TEMPLATE_REVISION = "2026-05-21-veeva-signature-page-v1"
KEY_FINDINGS_LIMIT = 20
SEVERITY_ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}
BLOCKED_KEYS = {"raw_payload_json", "raw_payload", "sessionid", "session_id", "session"}
PREVIEWABLE_REPORT_STATUSES = {"DRAFT", "UNDER_REVIEW", "APPROVED", "REJECTED", "CHANGES_REQUESTED", "SUPERSEDED"}
DOWNLOADABLE_REPORT_STATUSES = {"APPROVED"}
FINAL_REPORT_STATUS = "APPROVED"
FINAL_DECISION_STATUSES = {"APPROVED", "REJECTED", "CHANGES_REQUESTED"}


@dataclass(frozen=True)
class AuditReviewPdfDisplayConfig:
    report_title: str = REPORT_TITLE
    application_name: str = APPLICATION_NAME
    confidentiality_label: str = CONFIDENTIALITY_LABEL
    scoring_basis: str = "10-point deterministic audit trail checklist"
    pending_signature_message: str = "Electronic Signature: Pending final QA approval."
    not_approved_signature_message: str = "Electronic Signature: Not applicable because the report was not approved."
    approved_signature_missing_message: str = "Electronic Signature: Not captured for the approved report."
    pending_hash_message: str = "Pending first approved PDF download."
    pending_approval_hash_message: str = "Pending final approval/download."
    not_approved_hash_message: str = "Not applicable because the report was not approved as final evidence."
    pending_qa_action: str = "QA review is required before the report can be used as controlled compliance evidence."
    decision_required_action: str = "Address captured reviewer comments before resubmission or closure."
    no_additional_action: str = "No additional QA required actions were captured in the report data."
    high_critical_action: str = (
        "Evaluate high or critical findings for deviation/CAPA applicability according to approved procedure."
    )
    system_notes: tuple[str, ...] = (
        "Generated by Compliance Manager / ValidateNow.",
        "Deterministic checks used.",
        "Raw audit payload is not included unless attached separately.",
        "Human approval required unless status is APPROVED.",
        "Approved reports are controlled compliance evidence.",
    )


PDF_DISPLAY_CONFIG = AuditReviewPdfDisplayConfig()


@dataclass(frozen=True)
class AuditReviewPdfDownload:
    file_name: str
    media_type: str
    content: bytes


def _utc_now() -> datetime:
    return datetime.now(UTC)


def _to_utc(value: datetime) -> datetime:
    if value.tzinfo is None or value.tzinfo.utcoffset(value) is None:
        return value.replace(tzinfo=UTC)
    return value.astimezone(UTC)


def _iso_datetime(value: datetime | None) -> str | None:
    if value is None:
        return None
    return _to_utc(value).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _safe_str(value: Any, fallback: str = "N/A") -> str:
    if value is None:
        return fallback
    text = str(value).strip()
    return text or fallback


def _first_present(*values: Any) -> Any:
    for value in values:
        if value is None:
            continue
        if isinstance(value, str) and not value.strip():
            continue
        return value
    return None


def _safe_int(value: Any, fallback: int = 0) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return fallback


def _as_dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _as_list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def _sanitize_value(value: Any) -> Any:
    if isinstance(value, dict):
        clean: dict[str, Any] = {}
        for key, item in value.items():
            normalized_key = str(key).replace("-", "_").lower()
            if normalized_key in BLOCKED_KEYS:
                continue
            clean[str(key)] = _sanitize_value(item)
        return clean
    if isinstance(value, list):
        return [_sanitize_value(item) for item in value]
    return value


def _format_label(value: Any) -> str:
    text = _safe_str(value)
    if text == "N/A":
        return text
    return " ".join(part if len(part) <= 4 else part.capitalize() for part in re.split(r"[_\s-]+", text) if part)


def _report_status_label(value: Any) -> str:
    status = _safe_str(value, "").upper()
    if status == "UNDER_REVIEW":
        return "SUBMITTED"
    if status == "CHANGES_REQUESTED":
        return "CHANGES REQUESTED"
    return _format_label(status) if status else "N/A"


def _format_datetime(value: Any) -> str:
    if isinstance(value, datetime):
        return _safe_str(_iso_datetime(value))
    if value is None:
        return "N/A"
    return _safe_str(value)


def _format_list(value: Any, fallback: str = "N/A") -> str:
    if isinstance(value, list):
        values = [_safe_str(item, "") for item in value]
        joined = ", ".join(item for item in values if item)
        return joined or fallback
    if isinstance(value, tuple):
        return _format_list(list(value), fallback)
    return _safe_str(value, fallback)


def _display_actor(
    workflow_metadata: dict[str, Any],
    prefix: str,
    *,
    fallback: Any = None,
    unavailable: str = "Not captured",
) -> str:
    actor_type = _safe_str(workflow_metadata.get(f"{prefix}_actor_type"), "").upper()
    name = _safe_str(workflow_metadata.get(f"{prefix}_name"), "")
    email = _safe_str(workflow_metadata.get(f"{prefix}_email"), "")
    user_id = _safe_str(workflow_metadata.get(f"{prefix}_user_id"), "")
    fallback_text = _safe_str(fallback, "")

    if actor_type == ACTOR_TYPE_SYSTEM or name == DEFAULT_SYSTEM_ACTOR or fallback_text == DEFAULT_SYSTEM_ACTOR:
        return "System Scheduler"
    if name and email and name.lower() != email.lower():
        return f"{name} <{email}>"
    if email:
        return email
    if name:
        return name
    if user_id:
        return user_id
    if fallback_text:
        return fallback_text
    return unavailable


def _display_actor_name(
    workflow_metadata: dict[str, Any],
    prefix: str,
    *,
    fallback: Any = None,
    unavailable: str = "Not captured",
) -> str:
    actor_type = _safe_str(workflow_metadata.get(f"{prefix}_actor_type"), "").upper()
    name = _safe_str(workflow_metadata.get(f"{prefix}_name"), "")
    email = _safe_str(workflow_metadata.get(f"{prefix}_email"), "")
    fallback_text = _safe_str(fallback, "")

    if actor_type == ACTOR_TYPE_SYSTEM or name == DEFAULT_SYSTEM_ACTOR or fallback_text == DEFAULT_SYSTEM_ACTOR:
        return "System Scheduler"
    if name:
        return name
    if email:
        return email
    if fallback_text:
        return fallback_text
    return unavailable


def _format_actor_roles(value: Any, fallback: str = "") -> str:
    if isinstance(value, list):
        roles = [_safe_str(item, "") for item in value]
        return ", ".join(role for role in roles if role) or fallback
    return _safe_str(value, fallback)


def _format_actor_role_name(name: str, roles: Any, actor_type: str = "") -> str:
    role_text = "SYSTEM" if actor_type.upper() == ACTOR_TYPE_SYSTEM else _format_actor_roles(roles)
    if role_text and name:
        return f"{role_text} - {name}"
    return name or role_text or "Not captured"


def _display_actor_role_name(
    workflow_metadata: dict[str, Any],
    prefix: str,
    *,
    fallback: Any = None,
    fallback_roles: Any = None,
) -> str:
    actor_type = _safe_str(workflow_metadata.get(f"{prefix}_actor_type"), "").upper()
    name = _display_actor_name(workflow_metadata, prefix, fallback=fallback)
    roles = workflow_metadata.get(f"{prefix}_roles") or fallback_roles
    return _format_actor_role_name(name, roles, actor_type)


def _display_actor_user_id(
    workflow_metadata: dict[str, Any],
    prefix: str,
    *,
    fallback: Any = None,
    unavailable: str = "Not captured",
) -> str:
    actor_type = _safe_str(workflow_metadata.get(f"{prefix}_actor_type"), "").upper()
    user_id = _safe_str(workflow_metadata.get(f"{prefix}_user_id"), "")
    fallback_text = _safe_str(fallback, "")

    if actor_type == ACTOR_TYPE_SYSTEM:
        return "SYSTEM"
    return user_id or fallback_text or unavailable


def _job_run_actor(job: Any) -> dict[str, Any]:
    if job is None:
        return {}
    actor_sources = [
        _as_dict(_as_dict(getattr(job, "analysis_summary_json", None)).get("analyzed_actor")),
        _as_dict(_as_dict(getattr(job, "extraction_summary_json", None)).get("extracted_actor")),
        _as_dict(_as_dict(getattr(job, "input_snapshot_json", None)).get("requested_actor")),
    ]
    return next((actor for actor in actor_sources if actor), {})


def _job_run_actor_name(job: Any) -> str | None:
    actor = _job_run_actor(job)
    return (
        _safe_str(actor.get("display_name"), "")
        or _safe_str(actor.get("full_name"), "")
        or _safe_str(actor.get("name"), "")
        or _safe_str(actor.get("email"), "")
        or None
    )


def _job_run_actor_roles(job: Any) -> list[Any]:
    actor = _job_run_actor(job)
    roles = actor.get("roles")
    if not isinstance(roles, list):
        roles = actor.get("actor_roles")
    return roles if isinstance(roles, list) else []


def _job_run_actor_user_id(job: Any) -> str | None:
    actor = _job_run_actor(job)
    if _safe_str(actor.get("actor_type"), "").upper() == ACTOR_TYPE_SYSTEM or _job_run_actor_name(job) == DEFAULT_SYSTEM_ACTOR:
        return "SYSTEM"
    return _safe_str(actor.get("user_id") or actor.get("actor_user_id"), "") or None


def _stage_fallback(report_status: str, stage: str) -> str:
    status = _safe_str(report_status, "").upper()
    if stage == "submission" and status in {"DRAFT", "SUPERSEDED"}:
        return "Pending"
    if stage in {"review", "decision"} and status in {"DRAFT", "UNDER_REVIEW", "SUPERSEDED"}:
        return "Pending"
    return "Not captured"


def _value_or_stage(value: Any, report_status: str, stage: str) -> str:
    text = _safe_str(value, "")
    return text if text else _stage_fallback(report_status, stage)


def _datetime_or_stage(value: Any, report_status: str, stage: str) -> str:
    text = _format_datetime(value)
    return text if text != "N/A" else _stage_fallback(report_status, stage)


def _risk_level_for_rating(rating: Any, score: int) -> str:
    normalized = _safe_str(rating, "").upper()
    if normalized == "COMPLIANT":
        return "Low"
    if normalized == "MINOR_FINDINGS":
        return "Moderate"
    if normalized == "MAJOR_FINDINGS":
        return "High"
    if normalized == "CRITICAL_RISK":
        return "Critical"
    if score >= 90:
        return "Low"
    if score >= 75:
        return "Moderate"
    if score >= 60:
        return "High"
    return "Critical"


def _score_interpretation(score: int, rating: Any) -> str:
    normalized = _safe_str(rating, "").upper()
    interpretations = {
        "COMPLIANT": "Configured checks did not identify material compliance risk within the selected scope.",
        "MINOR_FINDINGS": "Findings indicate limited compliance risk and should be reviewed before closure.",
        "MAJOR_FINDINGS": "Findings indicate elevated compliance risk and require QA review and documented follow-up.",
        "CRITICAL_RISK": "Findings indicate critical compliance risk and require QA assessment before closure.",
    }
    if normalized in interpretations:
        return interpretations[normalized]
    return (
        "The score was calculated from configured deterministic audit trail checks; "
        f"a score of {score}/100 should be interpreted using the configured scoring bands."
    )


def _score_impact_label(value: Any) -> str:
    impact = _safe_int(value, 0)
    if impact > 0:
        return f"-{impact}"
    if impact == 0:
        return "0"
    return _safe_str(value)


def _sanitize_filename_part(value: Any) -> str:
    text = _safe_str(value, "asset").strip()
    text = re.sub(r"[^A-Za-z0-9._-]+", "-", text)
    text = text.strip(".-")
    return text or "asset"


def _file_storage_root() -> Path:
    return Path(get_settings().FILE_STORAGE_DIR).resolve()


def _safe_relative_to(path: Path, root: Path) -> str:
    resolved = path.resolve()
    root = root.resolve()
    try:
        return resolved.relative_to(root).as_posix()
    except ValueError as exc:
        raise AuditReviewValidationError("Final PDF path is outside configured file storage.") from exc


def _final_pdf_storage_path(report: AuditReviewReport, file_name: str) -> tuple[Path, str]:
    storage_root = _file_storage_root()
    target_dir = storage_root / "audit_review_reports" / "final" / str(report.report_id)
    target_dir.mkdir(parents=True, exist_ok=True)
    target_path = (target_dir / Path(file_name).name).resolve()
    relative_path = _safe_relative_to(target_path, storage_root)
    return target_path, f"filestorage/{relative_path}"


def _resolve_final_pdf_path(value: str | None) -> Path | None:
    text = _safe_str(value, "")
    if not text:
        return None
    normalized = text.replace("\\", "/").lstrip("/")
    if normalized.startswith("filestorage/"):
        normalized = normalized.removeprefix("filestorage/")
    candidate = (_file_storage_root() / normalized).resolve()
    _safe_relative_to(candidate, _file_storage_root())
    return candidate


def _read_final_pdf_bytes(report: AuditReviewReport) -> bytes | None:
    path = _resolve_final_pdf_path(report.final_pdf_path)
    if path is None or not path.is_file():
        return None
    content = path.read_bytes()
    if report.final_pdf_hash:
        digest = hashlib.sha256(content).hexdigest()
        if digest.lower() != report.final_pdf_hash.lower():
            raise AuditReviewValidationError(
                "Stored final PDF integrity check failed.",
                data={"report_id": str(report.report_id)},
            )
    return content


def _stored_pdf_template_revision(report: AuditReviewReport) -> str:
    metadata = _as_dict(report.workflow_metadata_json)
    final_report = _as_dict(metadata.get("final_report"))
    summary = _as_dict(report.report_summary_json)
    return _safe_str(_first_present(final_report.get("pdf_template_revision"), summary.get("pdf_template_revision")), "")


def _stored_pdf_uses_current_template(report: AuditReviewReport) -> bool:
    return _stored_pdf_template_revision(report) == PDF_TEMPLATE_REVISION


async def _persist_final_pdf(
    db: AsyncSession,
    report: AuditReviewReport,
    *,
    file_name: str,
    content: bytes,
    refresh_template: bool = False,
) -> None:
    target_path, stored_path = _final_pdf_storage_path(report, file_name)
    if report.is_locked and report.final_pdf_path and not refresh_template:
        existing = _read_final_pdf_bytes(report)
        if existing is not None:
            return
        raise AuditReviewValidationError(
            "Locked approved report has a final PDF path but the file could not be read.",
            data={"report_id": str(report.report_id), "final_pdf_path": report.final_pdf_path},
        )

    target_path.write_bytes(content)
    digest = hashlib.sha256(content).hexdigest()
    report.final_pdf_path = stored_path
    report.final_pdf_hash = digest
    report.file_path = report.file_path or stored_path
    report.report_version = report.report_version or get_audit_review_workflow_config().report_version
    workflow_metadata = update_final_pdf_metadata(
        report.workflow_metadata_json,
        final_pdf_path=stored_path,
        final_pdf_hash=digest,
        report_version=report.report_version,
    )
    final_report = dict(_as_dict(workflow_metadata.get("final_report")))
    final_report["pdf_template_revision"] = PDF_TEMPLATE_REVISION
    workflow_metadata["final_report"] = final_report
    report.workflow_metadata_json = workflow_metadata
    summary = dict(report.report_summary_json or {})
    summary["final_pdf_path"] = stored_path
    summary["final_pdf_hash"] = digest
    summary["report_version"] = report.report_version
    summary["pdf_template_revision"] = PDF_TEMPLATE_REVISION
    report.report_summary_json = summary
    report.modified_dt = _utc_now()
    await db.commit()


def _asset_code(asset: Asset | None, fallback: uuid.UUID) -> str:
    return _safe_str(getattr(asset, "asset_id", None), str(fallback))


def _approval_decision(report: AuditReviewReport) -> dict[str, Any]:
    return _as_dict(_sanitize_value(report.approval_decision_json or {}))


def _submission_notes(report: AuditReviewReport) -> str:
    decision = _approval_decision(report)
    submission = _as_dict(decision.get("submission"))
    return _safe_str(submission.get("submission_notes"), "N/A")


def _workflow_text(
    workflow_metadata: dict[str, Any],
    key: str,
    *,
    fallback: Any = None,
    unavailable: str = "Not captured",
) -> str:
    value = _first_present(workflow_metadata.get(key), fallback)
    return _safe_str(value, unavailable)


def _severity_counts(findings: list[AuditReviewFinding], report_json: dict[str, Any]) -> dict[str, int]:
    report_summary = _as_dict(report_json.get("finding_summary"))
    if report_summary:
        return {
            "critical": _safe_int(_first_present(report_summary.get("critical"), report_summary.get("CRITICAL"))),
            "high": _safe_int(_first_present(report_summary.get("high"), report_summary.get("HIGH"))),
            "medium": _safe_int(_first_present(report_summary.get("medium"), report_summary.get("MEDIUM"))),
            "low": _safe_int(_first_present(report_summary.get("low"), report_summary.get("LOW"))),
        }

    counter = Counter(_safe_str(finding.severity, "LOW").upper() for finding in findings)
    return {
        "critical": counter.get("CRITICAL", 0),
        "high": counter.get("HIGH", 0),
        "medium": counter.get("MEDIUM", 0),
        "low": counter.get("LOW", 0),
    }


def _severity_summary_from_counts(severity_counts: dict[str, int]) -> list[list[Any]]:
    return [
        ["CRITICAL", severity_counts.get("critical", 0)],
        ["HIGH", severity_counts.get("high", 0)],
        ["MEDIUM", severity_counts.get("medium", 0)],
        ["LOW", severity_counts.get("low", 0)],
    ]


def _finding_reviewer_comment(source: dict[str, Any]) -> str:
    evidence = _as_dict(source.get("evidence_json") or source.get("evidence"))
    return _safe_str(
        _first_present(
            source.get("reviewer_comment"),
            source.get("reviewer_comments"),
            evidence.get("reviewer_comment"),
            evidence.get("reviewer_comments"),
        ),
        "N/A",
    )


def _extraction_summary_rows(summary: dict[str, Any]) -> list[list[str]]:
    rows: list[list[str]] = []
    for key, value in summary.items():
        if isinstance(value, (dict, list)):
            display = str(_sanitize_value(value))
        else:
            display = _safe_str(value)
        rows.append([_format_label(key), display])
    return rows or [["Extraction Summary", "N/A"]]


def _score_rows(scores: list[AuditReviewScore], report_json: dict[str, Any]) -> list[dict[str, Any]]:
    if scores:
        return [
            {
                "check_code": score.check_code,
                "check_name": score.check_name,
                "finding_count": score.finding_count,
                "penalty_points": score.applied_penalty,
                "status": score.score_status,
                "score_impact": _score_impact_label(score.applied_penalty),
            }
            for score in scores
            if score.score_scope == "CHECKPOINT"
        ]

    return [
        {
            "check_code": item.get("check_code"),
            "check_name": item.get("check_name"),
            "finding_count": item.get("finding_count"),
            "penalty_points": item.get("penalty_points"),
            "status": item.get("status"),
            "score_impact": _score_impact_label(item.get("penalty_points")),
        }
        for item in _as_list(report_json.get("check_summary"))
        if isinstance(item, dict)
    ]


def _severity_summary_rows(findings: list[AuditReviewFinding], report_json: dict[str, Any]) -> list[list[Any]]:
    return _severity_summary_from_counts(_severity_counts(findings, report_json))


def _key_finding_rows(findings: list[AuditReviewFinding], report_json: dict[str, Any]) -> list[dict[str, Any]]:
    if findings:
        sorted_findings = sorted(
            findings,
            key=lambda finding: (
                SEVERITY_ORDER.get(_safe_str(finding.severity, "LOW").upper(), 99),
                finding.created_dt,
                str(finding.finding_id),
            ),
        )
        return [
            {
                "severity": _safe_str(finding.severity, "LOW").upper(),
                "check": finding.check_code,
                "title": finding.finding_title or finding.title or finding.check_name,
                "source_record_count": finding.source_record_count,
                "score_impact": finding.score_impact,
                "reviewer_comment": _finding_reviewer_comment(finding.evidence_json or {}),
                "review_status": finding.status,
            }
            for finding in sorted_findings[:KEY_FINDINGS_LIMIT]
        ]

    rows: list[dict[str, Any]] = []
    for item in _as_list(report_json.get("key_findings"))[:KEY_FINDINGS_LIMIT]:
        if not isinstance(item, dict):
            continue
        rows.append(
            {
                "severity": item.get("severity"),
                "check": item.get("check_code"),
                "title": item.get("finding_title"),
                "source_record_count": item.get("source_record_count"),
                "score_impact": item.get("score_impact", "N/A"),
                "reviewer_comment": _finding_reviewer_comment(item),
                "review_status": item.get("review_status") or item.get("status"),
            }
        )
    return rows


def _recommendations(report_json: dict[str, Any], markdown: str | None) -> list[str]:
    structured = [
        _safe_str(item, "")
        for item in _as_list(report_json.get("recommendations"))
        if _safe_str(item, "").strip()
    ]
    if structured:
        return structured

    recommendations: list[str] = []
    in_section = False
    for line in (markdown or "").splitlines():
        stripped = line.strip()
        if stripped.startswith("## "):
            in_section = stripped.lower().startswith("## 6. recommendations")
            continue
        if in_section and stripped.startswith("- "):
            recommendations.append(stripped[2:].strip())
    return recommendations


def _total_penalty(scores: list[AuditReviewScore], analysis_summary: dict[str, Any], overall_score: int) -> int:
    overall_row = next(
        (
            score
            for score in scores
            if score.check_code == OVERALL_CHECK_CODE and score.score_scope == "OVERALL"
        ),
        None,
    )
    if overall_row is not None:
        return _safe_int(overall_row.applied_penalty)
    value = _first_present(analysis_summary.get("total_applied_penalty"), analysis_summary.get("applied_penalty"))
    if value is not None:
        return _safe_int(value)
    return max(0, 100 - overall_score)


def _records_by_audit_type_rows(execution: dict[str, Any], extraction_summary: dict[str, Any]) -> list[list[Any]]:
    records_by_type = _as_dict(execution.get("records_by_audit_type"))
    coverage = _as_dict(execution.get("extraction_coverage_by_audit_type")) or _as_dict(extraction_summary.get("audit_types"))
    audit_types = sorted({*records_by_type.keys(), *coverage.keys()})
    rows: list[list[Any]] = []
    for audit_type in audit_types:
        coverage_item = _as_dict(coverage.get(audit_type))
        rows.append(
            [
                audit_type,
                _safe_str(coverage_item.get("status"), "N/A"),
                _safe_int(_first_present(records_by_type.get(audit_type), coverage_item.get("record_count"))),
            ]
        )
    return rows


def _normalization_error_count(extraction_summary: dict[str, Any]) -> str:
    audit_types = _as_dict(extraction_summary.get("audit_types"))
    if not audit_types:
        return _safe_str(extraction_summary.get("normalization_error_count"), "N/A")
    return str(
        sum(
            _safe_int(_as_dict(item).get("normalization_error_count"))
            for item in audit_types.values()
            if isinstance(item, dict)
        )
    )


def _extraction_status(extraction_summary: dict[str, Any], job_status: Any) -> str:
    successful = _as_list(extraction_summary.get("successful_audit_trail_types"))
    failed = _as_list(extraction_summary.get("failed_audit_trail_types"))
    if successful and failed:
        return "PARTIAL_EXTRACTION"
    if successful:
        return "EXTRACTED"
    if failed:
        return "FAILED"
    return _safe_str(job_status)


def _business_hours(analysis_summary: dict[str, Any], input_snapshot: dict[str, Any]) -> str:
    timezone_name = _first_present(analysis_summary.get("business_timezone"), input_snapshot.get("business_timezone"))
    start_hour = _first_present(analysis_summary.get("business_start_hour"), input_snapshot.get("business_start_hour"))
    end_hour = _first_present(analysis_summary.get("business_end_hour"), input_snapshot.get("business_end_hour"))
    if timezone_name is None and start_hour is None and end_hour is None:
        return "N/A"
    if start_hour is not None and end_hour is not None:
        return f"{_safe_str(timezone_name)}; {_safe_int(start_hour):02d}:00 to {_safe_int(end_hour):02d}:00"
    return _safe_str(timezone_name)


def _required_actions(
    report_status: str,
    severity_counts: dict[str, int],
    report_json: dict[str, Any],
    config: AuditReviewPdfDisplayConfig,
) -> list[str]:
    actions = [
        _safe_str(item, "")
        for item in _as_list(_first_present(report_json.get("qa_required_actions"), report_json.get("required_actions")))
        if _safe_str(item, "").strip()
    ]
    if severity_counts.get("critical", 0) > 0 or severity_counts.get("high", 0) > 0:
        actions.append(config.high_critical_action)
    if actions:
        return actions
    status = _safe_str(report_status, "").upper()
    if status in {"REJECTED", "CHANGES_REQUESTED"}:
        return [config.decision_required_action]
    if status == "APPROVED":
        return [config.no_additional_action]
    return [config.pending_qa_action]


def _overall_conclusion(
    severity_counts: dict[str, int],
    total_findings: int,
    score: int,
    rating: str,
) -> str:
    rating_label = _format_label(rating)
    if total_findings <= 0:
        return (
            "The review identified no findings for the selected audit trail records. "
            f"Based on the configured scoring rules, this review is classified as {rating_label}."
        )
    if severity_counts.get("critical", 0) > 0 or severity_counts.get("high", 0) > 0:
        return (
            "The review identified high or critical findings that require QA review and possible deviation/CAPA "
            f"assessment. The calculated score is {score}/100 and the review is classified as {rating_label}."
        )
    return (
        f"The review identified findings requiring QA review. The calculated score is {score}/100 and the review "
        f"is classified as {rating_label}."
    )


def _executive_summary_paragraph(context: dict[str, Any]) -> str:
    critical = context["severity_counts"].get("critical", 0)
    high = context["severity_counts"].get("high", 0)
    medium = context["severity_counts"].get("medium", 0)
    low = context["severity_counts"].get("low", 0)
    total_findings = context["total_findings"]
    base = (
        f"This audit trail review was performed for {context['asset_name']} covering the period "
        f"{context['review_start_dt']} to {context['review_end_dt']}. A total of "
        f"{context['total_records_reviewed']} audit trail records were reviewed. "
    )
    if total_findings <= 0:
        findings_sentence = "The review identified no findings for the selected audit trail records. "
    else:
        findings_sentence = (
            f"The system identified {total_findings} findings: {critical} critical, {high} high, "
            f"{medium} medium, and {low} low. "
        )
    score_sentence = (
        f"The calculated compliance score is {context['overall_score']}/100 with a rating of "
        f"{_format_label(context['rating'])}. Based on the configured scoring rules, this review is "
        f"classified as {_format_label(context['rating'])}."
    )
    high_risk_sentence = (
        " The review identified high or critical findings that require QA review and possible deviation/CAPA assessment."
        if critical > 0 or high > 0
        else ""
    )
    return f"{base}{findings_sentence}{score_sentence}{high_risk_sentence}"


async def _load_export_context(
    db: AsyncSession,
    report_id: uuid.UUID,
    *,
    allowed_statuses: set[str] | None = None,
    status_error_message: str | None = None,
) -> dict[str, Any]:
    result = await db.execute(
        select(AuditReviewReport)
        .options(
            selectinload(AuditReviewReport.job).selectinload(AuditReviewJob.asset),
            selectinload(AuditReviewReport.asset),
        )
        .where(AuditReviewReport.report_id == report_id)
    )
    report = result.scalars().first()
    if report is None:
        raise AuditReviewNotFoundError("Audit review report not found")
    allowed = allowed_statuses or PREVIEWABLE_REPORT_STATUSES
    if report.report_status not in allowed:
        raise AuditReviewValidationError(
            status_error_message
            or "Audit review report preview is available only after a report has been generated.",
            data={"report_id": str(report.report_id), "status": report.report_status},
        )

    job = report.job
    asset = report.asset or (job.asset if job is not None else None)
    scores_result = await db.execute(
        select(AuditReviewScore)
        .where(AuditReviewScore.job_id == report.job_id)
        .order_by(AuditReviewScore.sort_order.asc(), AuditReviewScore.check_code.asc())
    )
    findings_result = await db.execute(
        select(AuditReviewFinding)
        .where(AuditReviewFinding.job_id == report.job_id)
        .order_by(AuditReviewFinding.created_dt.asc(), AuditReviewFinding.finding_id.asc())
    )

    config = PDF_DISPLAY_CONFIG
    report_json = _as_dict(_sanitize_value(report.report_payload_json or {}))
    report_summary = _as_dict(_sanitize_value(report.report_summary_json or {}))
    workflow_metadata = build_report_workflow_metadata(report, job)
    review_scope = _as_dict(report_json.get("review_scope"))
    execution = _as_dict(report_json.get("execution_summary"))
    input_snapshot = _as_dict(_sanitize_value(getattr(job, "input_snapshot_json", {}) if job is not None else {}))
    extraction_summary = _as_dict(_sanitize_value(getattr(job, "extraction_summary_json", {}) if job is not None else {}))
    analysis_summary = _as_dict(_sanitize_value(getattr(job, "analysis_summary_json", {}) if job is not None else {}))
    scores = list(scores_result.scalars().all())
    findings = list(findings_result.scalars().all())
    export_generated_dt = _utc_now()
    generated_dt = report_summary.get("generated_at") or _iso_datetime(report.created_dt)
    asset_uuid = getattr(asset, "asset_uuid", None) or report.asset_id
    asset_code = _asset_code(asset, report.asset_id)
    file_name = f"audit-trail-review-{_sanitize_filename_part(asset_code)}-{report.report_id}.pdf"
    report_status = _safe_str(report.report_status, "DRAFT").upper()
    report_status_display = _report_status_label(report_status).upper()
    review_type = _safe_str(_first_present(workflow_metadata.get("review_type"), report.review_type), "ADHOC").upper()
    trigger_source = _safe_str(_first_present(workflow_metadata.get("trigger_source"), report.trigger_source), "MANUAL_USER").upper()
    review_start_dt = _format_datetime(_first_present(getattr(job, "review_start_dt", None), review_scope.get("review_start_dt")))
    review_end_dt = _format_datetime(_first_present(getattr(job, "review_end_dt", None), review_scope.get("review_end_dt")))
    severity_counts = _severity_counts(findings, report_json)
    total_findings = _safe_int(
        _first_present(execution.get("total_findings"), report_summary.get("total_findings"), sum(severity_counts.values()), len(findings))
    )
    total_records_reviewed = _safe_int(
        _first_present(execution.get("total_records_reviewed"), report_summary.get("total_records_reviewed"), extraction_summary.get("record_count"))
    )
    overall_score = _safe_int(_first_present(execution.get("overall_score"), report_summary.get("overall_score")))
    rating = _safe_str(_first_present(execution.get("rating"), report_summary.get("rating")))
    total_penalty = _total_penalty(scores, analysis_summary, overall_score)
    risk_level = _risk_level_for_rating(rating, overall_score)
    interpretation = _score_interpretation(overall_score, rating)
    schedule_id = _safe_str(_first_present(workflow_metadata.get("schedule_id"), report.schedule_id), "N/A")
    schedule_run_id = _safe_str(_first_present(workflow_metadata.get("schedule_run_id"), report.schedule_run_id), "N/A")
    schedule_name = _safe_str(_first_present(input_snapshot.get("schedule_name"), workflow_metadata.get("schedule_name")), "Not captured")
    submitted_by = _display_actor(
        workflow_metadata,
        "submitted_by",
        fallback=report.submitted_by,
        unavailable=_stage_fallback(report_status, "submission"),
    )
    reviewed_by = _display_actor(
        workflow_metadata,
        "reviewed_by",
        fallback=report.reviewed_by,
        unavailable=_stage_fallback(report_status, "review"),
    )
    decision_by = _display_actor(
        workflow_metadata,
        "decision_by",
        fallback=report.reviewed_by,
        unavailable=_stage_fallback(report_status, "decision"),
    )
    locked_by = _display_actor(workflow_metadata, "locked_by", unavailable="Not captured")
    e_signed_by = _display_actor(workflow_metadata, "e_signed_by", unavailable="Not captured")
    final_pdf_hash = _safe_str(_first_present(workflow_metadata.get("final_pdf_hash"), report.final_pdf_hash), "")
    final_pdf_hash_display = final_pdf_hash or (
        config.pending_hash_message
        if report_status == FINAL_REPORT_STATUS
        else config.pending_approval_hash_message
    )
    submitted_at = _datetime_or_stage(
        _first_present(workflow_metadata.get("submitted_at"), report.submitted_dt),
        report_status,
        "submission",
    )
    reviewed_at = _datetime_or_stage(
        _first_present(workflow_metadata.get("reviewed_at"), report.reviewed_dt),
        report_status,
        "review",
    )
    decision_at = _datetime_or_stage(
        _first_present(workflow_metadata.get("decision_at"), report.reviewed_dt),
        report_status,
        "decision",
    )
    submission_notes = _value_or_stage(
        _first_present(workflow_metadata.get("submission_notes"), _submission_notes(report)),
        report_status,
        "submission",
    )
    reviewer_comments = _value_or_stage(
        _first_present(workflow_metadata.get("reviewer_comments"), report.reviewer_comments),
        report_status,
        "review",
    )
    decision_comments = _value_or_stage(
        _first_present(workflow_metadata.get("decision_comments"), report.reviewer_comments),
        report_status,
        "decision",
    )
    signature_records = _signature_records(report, workflow_metadata)
    decision_status = _safe_str(_first_present(workflow_metadata.get("decision_status"), report_status), "PENDING").upper()
    final_decision = _report_status_label(decision_status if decision_status in FINAL_DECISION_STATUSES else report_status)
    score_label = _safe_str(_first_present(execution.get("score_label"), report_summary.get("score_label")), "Compliance Score")
    recommendations = _recommendations(report_json, report.report_markdown)
    required_actions = _required_actions(report_status, severity_counts, report_json, config)

    context = {
        "config": config,
        "report": report,
        "job": job,
        "asset": asset,
        "report_json": report_json,
        "report_summary": report_summary,
        "workflow_metadata": workflow_metadata,
        "review_scope": review_scope,
        "execution": execution,
        "input_snapshot": input_snapshot,
        "extraction_summary": extraction_summary,
        "analysis_summary": analysis_summary,
        "scores": _score_rows(scores, report_json),
        "severity_counts": severity_counts,
        "severity_summary": _severity_summary_from_counts(severity_counts),
        "key_findings": _key_finding_rows(findings, report_json),
        "recommendations": recommendations,
        "required_actions": required_actions,
        "asset_name": _safe_str(getattr(asset, "asset_name", None) or _as_dict(report_json.get("asset")).get("asset_name")),
        "asset_code": asset_code,
        "asset_uuid": str(asset_uuid),
        "generated_dt": _safe_str(generated_dt),
        "export_generated_dt": export_generated_dt,
        "file_name": file_name,
        "report_title": _safe_str(report_json.get("title"), config.report_title),
        "report_id": str(report.report_id),
        "report_status": report_status,
        "report_status_display": report_status_display,
        "report_version": _safe_str(_first_present(workflow_metadata.get("report_version"), report.report_version), get_audit_review_workflow_config().report_version),
        "review_type": review_type,
        "trigger_source": trigger_source,
        "veeva_instance_name": _safe_str(_first_present(getattr(job, "veeva_instance_name", None), review_scope.get("veeva_instance_name"))),
        "veeva_app_name": _safe_str(_first_present(getattr(job, "veeva_app_name", None), review_scope.get("veeva_app_name"))),
        "audit_trail_type": _safe_str(_first_present(getattr(job, "audit_trail_type", None), review_scope.get("audit_trail_type"))),
        "review_start_dt": review_start_dt,
        "review_end_dt": review_end_dt,
        "review_period": f"{review_start_dt} to {review_end_dt}",
        "total_records_reviewed": total_records_reviewed,
        "total_findings": total_findings,
        "overall_score": overall_score,
        "score_label": score_label,
        "rating": rating,
        "risk_level": risk_level,
        "total_penalty": total_penalty,
        "score_interpretation": interpretation,
        "score_basis": config.scoring_basis,
        "overall_conclusion": _overall_conclusion(severity_counts, total_findings, overall_score, rating),
        "review_job_id": _safe_str(getattr(job, "job_id", None)),
        "review_candidate_key": _safe_str(getattr(job, "review_candidate_key", None)),
        "trigger_mode": _safe_str(getattr(job, "trigger_mode", None)),
        "period_basis": _safe_str(getattr(job, "period_basis", None)),
        "requested_by": _safe_str(getattr(job, "requested_by", None)),
        "selected_audit_trail_types": _format_list(review_scope.get("selected_audit_trail_types") or input_snapshot.get("selected_audit_trail_types")),
        "business_hours": _business_hours(analysis_summary, input_snapshot),
        "schedule_id": schedule_id if review_type == "SCHEDULED" else "N/A - manual review",
        "schedule_name": schedule_name if review_type == "SCHEDULED" else "N/A - manual review",
        "schedule_run_id": schedule_run_id if review_type == "SCHEDULED" else "N/A - manual review",
        "records_by_audit_type_rows": _records_by_audit_type_rows(execution, extraction_summary),
        "extraction_status": _extraction_status(extraction_summary, getattr(job, "status", None)),
        "extracted_at": _safe_str(extraction_summary.get("extracted_at")),
        "failed_audit_trail_types": _format_list(extraction_summary.get("failed_audit_trail_types")),
        "successful_audit_trail_types": _format_list(extraction_summary.get("successful_audit_trail_types")),
        "normalization_error_count": _normalization_error_count(extraction_summary),
        "extraction_summary_rows": _extraction_summary_rows(extraction_summary),
        "approval_status": _report_status_label(_first_present(report_summary.get("approval_status"), report_status)),
        "workflow_status": report_status_display,
        "triggered_by": _display_actor(workflow_metadata, "triggered_by", fallback=getattr(job, "requested_by", None)),
        "run_by": _display_actor(workflow_metadata, "run_by", fallback=getattr(job, "modified_by", None)),
        "run_by_name": _display_actor_role_name(
            workflow_metadata,
            "run_by",
            fallback=_job_run_actor_name(job) or getattr(job, "modified_by", None),
            fallback_roles=_job_run_actor_roles(job),
        ),
        "run_by_user_id": _display_actor_user_id(workflow_metadata, "run_by", fallback=_job_run_actor_user_id(job)),
        "draft_generated_by": _display_actor(workflow_metadata, "draft_generated_by", fallback=report.created_by),
        "draft_generated_at": _safe_str(workflow_metadata.get("draft_generated_at"), _format_datetime(report.created_dt)),
        "submitted_by": submitted_by,
        "submitted_dt": submitted_at,
        "submission_notes": submission_notes,
        "reviewed_by": reviewed_by,
        "reviewed_dt": reviewed_at,
        "reviewer_comments": reviewer_comments,
        "decision_by": decision_by,
        "decision_dt": decision_at,
        "decision_comments": decision_comments,
        "decision_status": _report_status_label(decision_status),
        "final_decision": final_decision,
        "is_e_signed": bool(report.is_e_signed or workflow_metadata.get("is_e_signed")),
        "e_signed_at": _safe_str(_first_present(workflow_metadata.get("e_signed_at"), report.e_signed_at), "Not captured"),
        "e_signed_by": e_signed_by,
        "e_signed_by_roles": _format_list(workflow_metadata.get("e_signed_by_roles"), "Not captured"),
        "signature_meaning": _workflow_text(workflow_metadata, "signature_meaning", fallback=get_audit_review_workflow_config().signature_meaning),
        "authentication_method": _workflow_text(workflow_metadata, "authentication_method", fallback=get_audit_review_workflow_config().authentication_method),
        "signature_status": _safe_str(workflow_metadata.get("signature_status"), "NOT_SIGNED"),
        "signature_records": signature_records,
        "is_locked": bool(report.is_locked or workflow_metadata.get("is_locked")),
        "locked_at": _safe_str(_first_present(workflow_metadata.get("locked_at"), report.locked_at), "Not captured"),
        "locked_by": locked_by,
        "lock_status": "Locked" if bool(report.is_locked or workflow_metadata.get("is_locked")) else "Not Locked",
        "final_pdf_path": _safe_str(_first_present(workflow_metadata.get("final_pdf_path"), report.final_pdf_path), "N/A"),
        "final_pdf_hash": final_pdf_hash_display,
        "final_pdf_hash_raw": final_pdf_hash,
    }
    context["executive_summary_paragraph"] = _executive_summary_paragraph(context)
    return context


def _html_row(cells: list[Any], tag: str = "td") -> str:
    return "<tr>" + "".join(f"<{tag}>{escape(_safe_str(cell))}</{tag}>" for cell in cells) + "</tr>"


def _html_table(headers: list[str], rows: list[list[Any]]) -> str:
    body_rows = rows or [["N/A" for _ in headers]]
    return (
        "<table><thead>"
        + _html_row(headers, "th")
        + "</thead><tbody>"
        + "".join(_html_row(row) for row in body_rows)
        + "</tbody></table>"
    )


def _signature_record_text(record: dict[str, Any], *keys: str, fallback: str = "Not captured") -> str:
    for key in keys:
        value = record.get(key)
        if value is not None and str(value).strip():
            return str(value).strip()
    return fallback


def _signature_record_detail_lines(record: dict[str, Any]) -> list[str]:
    signer = _signature_record_text(record, "signature_name", "e_signed_by_name")
    title = _signature_record_text(record, "signature_title", "signature_role", fallback="")
    meaning = _signature_record_text(record, "signature_meaning")
    verdict = _signature_record_text(record, "signature_verdict", "verdict", fallback="Approved")
    signed_at = _signature_record_text(record, "signature_time", "e_signed_at")
    lines = [signer]
    if title:
        lines.append(title)
    lines.extend([meaning, verdict, signed_at])
    return lines


def _signature_records(report: AuditReviewReport, workflow_metadata: dict[str, Any]) -> list[dict[str, Any]]:
    stored = _as_dict(getattr(report, "workflow_metadata_json", None))
    stored_e_signature = _as_dict(stored.get("e_signature"))
    records = [
        _as_dict(item)
        for item in _as_list(stored_e_signature.get("signature_records"))
        if isinstance(item, dict)
    ]
    if records:
        return records

    approval_decision = _as_dict(getattr(report, "approval_decision_json", None))
    decision_e_signature = _as_dict(_as_dict(approval_decision.get("decision")).get("e_signature"))
    records = [
        _as_dict(item)
        for item in _as_list(decision_e_signature.get("signature_records"))
        if isinstance(item, dict)
    ]
    if records:
        return records

    if bool(getattr(report, "is_e_signed", None) or workflow_metadata.get("is_e_signed")):
        return [
            {
                "signature_type": "FINAL_QA_APPROVAL",
                "signature_name": _display_actor(workflow_metadata, "e_signed_by", fallback=getattr(report, "reviewed_by", None)),
                "signature_title": _format_list(workflow_metadata.get("e_signed_by_roles"), "Not captured"),
                "user_id": workflow_metadata.get("e_signed_by_user_id"),
                "user_email": workflow_metadata.get("e_signed_by_email"),
                "signature_time": _safe_str(_first_present(workflow_metadata.get("e_signed_at"), getattr(report, "e_signed_at", None)), "Not captured"),
                "signature_meaning": _safe_str(workflow_metadata.get("signature_meaning"), get_audit_review_workflow_config().signature_meaning),
                "signature_verdict": "Approved",
                "task_name": "Final QA Approval",
                "workflow_name": "Audit Review Report Approval",
                "workflow_step": "Approve Report",
                "authentication_method": _safe_str(workflow_metadata.get("authentication_method"), get_audit_review_workflow_config().authentication_method),
                "reviewer_comments": _safe_str(getattr(report, "reviewer_comments", None), "Not captured"),
                "report_id": str(report.report_id),
                "report_version": _safe_str(getattr(report, "report_version", None), get_audit_review_workflow_config().report_version),
            }
        ]
    return []


def _html_signature_page(context: dict[str, Any]) -> str:
    if context["report_status"] != FINAL_REPORT_STATUS or not context["signature_records"]:
        return ""
    rows = []
    for record in context["signature_records"]:
        step = _signature_record_text(record, "task_name", "workflow_step", fallback="Final QA Approval")
        details = "<br/>".join(escape(line) for line in _signature_record_detail_lines(record))
        rows.append(f"<tr><td>{escape(step)}</td><td>{details}</td></tr>")
    return f"""
  <div class="signature-page">
    <p class="meta">{escape(context["config"].confidentiality_label)} | {escape(context["config"].application_name)}</p>
    <h1>Electronic Signature Page</h1>
    <p class="meta">Signature Approval for {escape(context["report_version"])} {escape(context["report_id"])}</p>
    <table><tbody>{''.join(rows)}</tbody></table>
  </div>"""


def _signature_rows(context: dict[str, Any]) -> list[list[Any]]:
    config: AuditReviewPdfDisplayConfig = context["config"]
    if context["report_status"] == FINAL_REPORT_STATUS and context["is_e_signed"]:
        signature_record = context["signature_records"][0] if context["signature_records"] else {}
        return [
            ["Electronically Signed By", context["e_signed_by"]],
            ["User Email / User ID", _safe_str(_first_present(signature_record.get("user_email"), signature_record.get("user_id"), context["workflow_metadata"].get("e_signed_by_email"), context["workflow_metadata"].get("e_signed_by_user_id")), "Not captured")],
            ["Role at Time of Signature", context["e_signed_by_roles"]],
            ["Signature Meaning", context["signature_meaning"]],
            ["Signature Date/Time", context["e_signed_at"]],
            ["Authentication Method", context["authentication_method"]],
            ["Decision", context["final_decision"]],
            ["Comments", context["decision_comments"]],
            ["Report ID", context["report_id"]],
            ["Report Version", context["report_version"]],
        ]
    if context["report_status"] in {"REJECTED", "CHANGES_REQUESTED"}:
        return [["Electronic Signature", config.not_approved_signature_message]]
    if context["report_status"] == FINAL_REPORT_STATUS:
        return [["Electronic Signature", config.approved_signature_missing_message]]
    return [["Electronic Signature", config.pending_signature_message]]


def render_audit_review_report_html(context: dict[str, Any]) -> str:
    score_rows = [
        [
            row.get("check_code"),
            row.get("check_name"),
            row.get("finding_count"),
            row.get("penalty_points"),
            row.get("status"),
            row.get("score_impact"),
        ]
        for row in context["scores"]
    ]
    finding_rows = [
        [
            row.get("title"),
            row.get("severity"),
            row.get("check"),
            row.get("source_record_count"),
            row.get("score_impact"),
            row.get("reviewer_comment"),
            row.get("review_status"),
        ]
        for row in context["key_findings"]
    ]
    recommendation_items = "".join(f"<li>{escape(_safe_str(item))}</li>" for item in context["recommendations"])
    if not recommendation_items:
        recommendation_items = "<li>N/A</li>"
    required_action_items = "".join(f"<li>{escape(_safe_str(item))}</li>" for item in context["required_actions"]) or "<li>N/A</li>"
    system_note_items = "".join(f"<li>{escape(_safe_str(item))}</li>" for item in context["config"].system_notes)

    return f"""<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>{escape(context["report_title"])}</title>
  <style>
    body {{ color: #111827; font-family: Arial, sans-serif; margin: 32px; }}
    h1 {{ font-size: 24px; margin-bottom: 4px; }}
    h2 {{ border-bottom: 1px solid #d1d5db; font-size: 16px; margin-top: 28px; padding-bottom: 6px; }}
    p {{ font-size: 12px; line-height: 1.55; }}
    table {{ border-collapse: collapse; margin-top: 10px; width: 100%; }}
    th, td {{ border: 1px solid #d1d5db; font-size: 12px; padding: 7px; text-align: left; vertical-align: top; }}
    th {{ background: #f3f4f6; }}
    .meta {{ color: #4b5563; font-size: 12px; }}
    .badge {{ border: 1px solid #9ca3af; border-radius: 999px; display: inline-block; font-size: 12px; padding: 4px 10px; }}
    .score {{ background: #f8fafc; border: 1px solid #cbd5e1; padding: 10px; }}
    .signature-page {{ break-before: page; page-break-before: always; }}
    .signature-page h1 {{ text-align: center; }}
  </style>
</head>
<body>
  <p class="meta">{escape(context["config"].confidentiality_label)} | {escape(context["config"].application_name)}</p>
  <h1>{escape(context["report_title"])}</h1>
  <p><span class="badge">{escape(context["report_status_display"])}</span></p>
  {_html_table(["Report ID", "Generated date", "Report version", "Review Type"], [[context["report_id"], context["generated_dt"], context["report_version"], context["review_type"]]])}
  <h2>1. Executive Summary</h2>
  {_html_table(["Field", "Value"], [
      ["Audit review run by", context["run_by_name"]],
      ["Audit runner user ID", context["run_by_user_id"]],
  ])}
  <p>{escape(context["executive_summary_paragraph"])}</p>
  {_html_table(["Field", "Value"], [
      ["Review type", context["review_type"]],
      ["Trigger source", context["trigger_source"]],
      ["Asset/system", context["asset_name"]],
      ["Review period", context["review_period"]],
      ["Total records reviewed", context["total_records_reviewed"]],
      ["Total findings", context["total_findings"]],
      ["Critical findings", context["severity_counts"].get("critical", 0)],
      ["High findings", context["severity_counts"].get("high", 0)],
      ["Medium findings", context["severity_counts"].get("medium", 0)],
      ["Low findings", context["severity_counts"].get("low", 0)],
      ["Compliance Score", f'{context["overall_score"]} / 100'],
      ["Rating", _format_label(context["rating"])],
      ["Risk Level", context["risk_level"]],
      ["Overall conclusion", context["overall_conclusion"]],
  ])}
  <h2>2. Asset / System Information</h2>
  {_html_table(["Field", "Value"], [
      ["Asset name", context["asset_name"]],
      ["Asset ID/code", context["asset_code"]],
      ["Asset UUID", context["asset_uuid"]],
      ["Veeva instance", context["veeva_instance_name"]],
      ["Veeva app", context["veeva_app_name"]],
      ["Audit trail type", context["audit_trail_type"]],
  ])}
  <h2>3. Review Scope</h2>
  {_html_table(["Field", "Value"], [
      ["Manual or scheduled", context["review_type"]],
      ["Schedule ID", context["schedule_id"]],
      ["Schedule name", context["schedule_name"]],
      ["Schedule run ID", context["schedule_run_id"]],
      ["Review period", context["review_period"]],
      ["Selected audit trail types", context["selected_audit_trail_types"]],
      ["Review scope", _safe_str(context["review_scope"].get("review_scope"))],
      ["Timezone/business hours", context["business_hours"]],
      ["Review job ID", context["review_job_id"]],
      ["Review candidate key", context["review_candidate_key"]],
  ])}
  <h2>4. Audit Trail Analysis Summary</h2>
  {_html_table(["Field", "Value"], [
      ["Total records reviewed", context["total_records_reviewed"]],
      ["Extraction status", context["extraction_status"]],
      ["Extracted at", context["extracted_at"]],
      ["Failed audit trail types", context["failed_audit_trail_types"]],
      ["Successful audit trail types", context["successful_audit_trail_types"]],
      ["Normalization error count", context["normalization_error_count"]],
  ])}
  {_html_table(["Audit Trail Type", "Status", "Records"], context["records_by_audit_type_rows"])}
  <h2>5. Compliance Score / Checklist Summary</h2>
  <div class="score">
    {_html_table(["Field", "Value"], [
        ["Compliance Score", f'{context["overall_score"]} / 100'],
        ["Rating", _format_label(context["rating"])],
        ["Risk Level", context["risk_level"]],
        ["Scoring Basis", context["score_basis"]],
        ["Total Penalty Applied", context["total_penalty"]],
        ["Result Meaning", context["score_interpretation"]],
    ])}
  </div>
  {_html_table(["Check code", "Check name", "Findings", "Penalty", "Status", "Score impact"], score_rows)}
  <h2>6. Findings Summary</h2>
  {_html_table(["Severity", "Count"], context["severity_summary"])}
  <h2>7. Key Findings</h2>
  {_html_table(["Finding title", "Severity", "Check code", "Source record count", "Score impact", "Reviewer comment", "Review status"], finding_rows)}
  <h2>8. Recommendations and Required Actions</h2>
  <h3>System-generated recommendations</h3>
  <ul>{recommendation_items}</ul>
  <h3>QA required actions</h3>
  <ul>{required_action_items}</ul>
  <h2>9. QA Review / Approval</h2>
  {_html_table(["Field", "Value"], [
      ["Current decision/status", context["final_decision"]],
      ["Submitted by", context["submitted_by"]],
      ["Submitted date", context["submitted_dt"]],
      ["Submission notes", context["submission_notes"]],
      ["QA reviewer / approver", context["decision_by"]],
      ["QA decision date", context["decision_dt"]],
      ["QA comments", context["decision_comments"]],
  ])}
  <h2>10. Electronic Signature</h2>
  {_html_table(["Field", "Value"], _signature_rows(context))}
  <h2>11. System Notes</h2>
  <ul>{system_note_items}</ul>
  {_html_signature_page(context)}
</body>
</html>"""


def _pdf_paragraph(text: Any, style: Any) -> Any:
    from reportlab.platypus import Paragraph

    return Paragraph(escape(_safe_str(text)), style)


def _pdf_table(headers: list[str], rows: list[list[Any]], widths: list[float], styles: dict[str, Any]) -> Any:
    from reportlab.lib import colors
    from reportlab.platypus import Table, TableStyle

    table_rows = [[_pdf_paragraph(header, styles["table_header"]) for header in headers]]
    source_rows = rows or [["N/A" for _ in headers]]
    for row in source_rows:
        padded = [*row, *([""] * max(0, len(headers) - len(row)))]
        table_rows.append([_pdf_paragraph(cell, styles["table_cell"]) for cell in padded[: len(headers)]])

    table = Table(table_rows, colWidths=widths, repeatRows=1, hAlign="LEFT")
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5e7eb")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#111827")),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    return table


def _pdf_multiline_paragraph(lines: list[str], style: Any) -> Any:
    from reportlab.platypus import Paragraph

    return Paragraph("<br/>".join(escape(_safe_str(line)) for line in lines), style)


def _pdf_signature_block_table(context: dict[str, Any], widths: list[float], styles: dict[str, Any]) -> Any:
    from reportlab.lib import colors
    from reportlab.platypus import Table, TableStyle

    table_rows = [
        [
            _pdf_paragraph("Workflow Step", styles["table_header"]),
            _pdf_paragraph("Signature Details", styles["table_header"]),
        ]
    ]
    for record in context["signature_records"] or []:
        step = _signature_record_text(record, "task_name", "workflow_step", fallback="Final QA Approval")
        table_rows.append(
            [
                _pdf_paragraph(step, styles["table_cell"]),
                _pdf_multiline_paragraph(_signature_record_detail_lines(record), styles["table_cell"]),
            ]
        )
    if len(table_rows) == 1:
        table_rows.append(
            [
                _pdf_paragraph("Electronic Signature", styles["table_cell"]),
                _pdf_paragraph(context["config"].approved_signature_missing_message, styles["table_cell"]),
            ]
        )

    table = Table(table_rows, colWidths=widths, repeatRows=1, hAlign="LEFT")
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5e7eb")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#111827")),
                ("GRID", (0, 0), (-1, -1), 0.45, colors.HexColor("#94a3b8")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 7),
                ("RIGHTPADDING", (0, 0), (-1, -1), 7),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    return table


def _draw_footer(canvas: Any, doc: Any, generated_dt: datetime) -> None:
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColorRGB(0.35, 0.38, 0.44)
    canvas.drawString(doc.leftMargin, 0.42 * 72, CONFIDENTIALITY_LABEL)
    canvas.drawCentredString(doc.pagesize[0] / 2, 0.42 * 72, f"Generated {_safe_str(_iso_datetime(generated_dt))}")
    canvas.drawRightString(doc.pagesize[0] - doc.rightMargin, 0.42 * 72, f"Page {canvas.getPageNumber()}")
    canvas.restoreState()


def _build_pdf_bytes(context: dict[str, Any]) -> bytes:
    try:
        from reportlab.lib import colors
        from reportlab.lib.enums import TA_CENTER
        from reportlab.lib.pagesizes import LETTER
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import inch
        from reportlab.platypus import PageBreak, SimpleDocTemplate, Spacer
    except ImportError as exc:
        raise AuditReviewValidationError(
            "ReportLab is required for audit review PDF export. Install dependencies from requirements.txt.",
            data={"dependency": "reportlab"},
        ) from exc

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=LETTER,
        rightMargin=0.55 * inch,
        leftMargin=0.55 * inch,
        topMargin=0.55 * inch,
        bottomMargin=0.75 * inch,
        title=context["report_title"],
        author=context["config"].application_name,
        pageCompression=0,
    )
    base = getSampleStyleSheet()
    styles = {
        "app": ParagraphStyle("App", parent=base["Normal"], textColor=colors.HexColor("#475569"), fontSize=9),
        "controlled": ParagraphStyle(
            "Controlled",
            parent=base["Normal"],
            alignment=TA_CENTER,
            textColor=colors.HexColor("#7f1d1d"),
            fontSize=9,
            leading=11,
            fontName="Helvetica-Bold",
        ),
        "title": ParagraphStyle("Title", parent=base["Title"], fontSize=19, leading=24, alignment=TA_CENTER),
        "status": ParagraphStyle(
            "Status",
            parent=base["Normal"],
            alignment=TA_CENTER,
            borderColor=colors.HexColor("#94a3b8"),
            borderPadding=5,
            borderRadius=6,
            fontSize=10,
            leading=12,
        ),
        "section": ParagraphStyle(
            "Section",
            parent=base["Heading2"],
            fontSize=13,
            leading=16,
            spaceBefore=14,
            textColor=colors.HexColor("#0f172a"),
        ),
        "table_header": ParagraphStyle("TableHeader", parent=base["Normal"], fontSize=8, leading=10, fontName="Helvetica-Bold"),
        "table_cell": ParagraphStyle("TableCell", parent=base["Normal"], fontSize=8, leading=10),
        "summary": ParagraphStyle("Summary", parent=base["Normal"], fontSize=9, leading=13, spaceAfter=6),
        "note": ParagraphStyle("Note", parent=base["Normal"], fontSize=9, leading=12),
        "signature_heading": ParagraphStyle(
            "SignatureHeading",
            parent=base["Heading1"],
            alignment=TA_CENTER,
            fontSize=18,
            leading=22,
            spaceAfter=8,
            textColor=colors.HexColor("#0f172a"),
        ),
    }

    content: list[Any] = [
        _pdf_paragraph(context["config"].confidentiality_label, styles["controlled"]),
        _pdf_paragraph(context["config"].application_name, styles["app"]),
        _pdf_paragraph(context["report_title"], styles["title"]),
        _pdf_paragraph(context["report_status_display"], styles["status"]),
        Spacer(1, 8),
        _pdf_table(
            ["Report ID", "Generated date", "Report version", "Review Type"],
            [[context["report_id"], context["generated_dt"], context["report_version"], context["review_type"]]],
            [2.45 * inch, 1.85 * inch, 1.1 * inch, 1.1 * inch],
            styles,
        ),
        _pdf_paragraph("1. Executive Summary", styles["section"]),
        _pdf_table(
            ["Field", "Value"],
            [
                ["Audit review run by", context["run_by_name"]],
                ["Audit runner user ID", context["run_by_user_id"]],
            ],
            [2.1 * inch, 4.8 * inch],
            styles,
        ),
        _pdf_paragraph(context["executive_summary_paragraph"], styles["summary"]),
        _pdf_table(
            ["Field", "Value"],
            [
                ["Review type", context["review_type"]],
                ["Trigger source", context["trigger_source"]],
                ["Asset/system", context["asset_name"]],
                ["Review period", context["review_period"]],
                ["Total records reviewed", context["total_records_reviewed"]],
                ["Total findings", context["total_findings"]],
                ["Critical findings", context["severity_counts"].get("critical", 0)],
                ["High findings", context["severity_counts"].get("high", 0)],
                ["Medium findings", context["severity_counts"].get("medium", 0)],
                ["Low findings", context["severity_counts"].get("low", 0)],
                ["Compliance Score", f'{context["overall_score"]} / 100'],
                ["Rating", _format_label(context["rating"])],
                ["Risk Level", context["risk_level"]],
                ["Overall conclusion", context["overall_conclusion"]],
            ],
            [2.1 * inch, 4.8 * inch],
            styles,
        ),
        _pdf_paragraph("2. Asset / System Information", styles["section"]),
        _pdf_table(
            ["Field", "Value"],
            [
                ["Asset name", context["asset_name"]],
                ["Asset ID/code", context["asset_code"]],
                ["Asset UUID", context["asset_uuid"]],
                ["Veeva instance", context["veeva_instance_name"]],
                ["Veeva app", context["veeva_app_name"]],
                ["Audit trail type", context["audit_trail_type"]],
            ],
            [2.1 * inch, 4.8 * inch],
            styles,
        ),
        _pdf_paragraph("3. Review Scope", styles["section"]),
        _pdf_table(
            ["Field", "Value"],
            [
                ["Manual or scheduled", context["review_type"]],
                ["Schedule ID", context["schedule_id"]],
                ["Schedule name", context["schedule_name"]],
                ["Schedule run ID", context["schedule_run_id"]],
                ["Review period", context["review_period"]],
                ["Selected audit trail types", context["selected_audit_trail_types"]],
                ["Review scope", _safe_str(context["review_scope"].get("review_scope"))],
                ["Timezone/business hours", context["business_hours"]],
                ["Review job ID", context["review_job_id"]],
                ["Review candidate key", context["review_candidate_key"]],
            ],
            [2.1 * inch, 4.8 * inch],
            styles,
        ),
        _pdf_paragraph("4. Audit Trail Analysis Summary", styles["section"]),
        _pdf_table(
            ["Field", "Value"],
            [
                ["Total records reviewed", context["total_records_reviewed"]],
                ["Extraction status", context["extraction_status"]],
                ["Extracted at", context["extracted_at"]],
                ["Failed audit trail types", context["failed_audit_trail_types"]],
                ["Successful audit trail types", context["successful_audit_trail_types"]],
                ["Normalization error count", context["normalization_error_count"]],
            ],
            [2.1 * inch, 4.8 * inch],
            styles,
        ),
        Spacer(1, 6),
        _pdf_table(
            ["Audit Trail Type", "Status", "Records"],
            context["records_by_audit_type_rows"],
            [3.2 * inch, 1.8 * inch, 1.1 * inch],
            styles,
        ),
        _pdf_paragraph("5. Compliance Score / Checklist Summary", styles["section"]),
        _pdf_table(
            ["Field", "Value"],
            [
                ["Compliance Score", f'{context["overall_score"]} / 100'],
                ["Rating", _format_label(context["rating"])],
                ["Risk Level", context["risk_level"]],
                ["Scoring Basis", context["score_basis"]],
                ["Total Penalty Applied", context["total_penalty"]],
                ["Result Meaning", context["score_interpretation"]],
            ],
            [2.1 * inch, 4.8 * inch],
            styles,
        ),
        Spacer(1, 6),
        _pdf_table(
            ["Check code", "Check name", "Findings", "Penalty", "Status", "Score impact"],
            [
                [
                    row.get("check_code"),
                    row.get("check_name"),
                    row.get("finding_count"),
                    row.get("penalty_points"),
                    row.get("status"),
                    row.get("score_impact"),
                ]
                for row in context["scores"]
            ],
            [1.0 * inch, 2.3 * inch, 0.7 * inch, 0.7 * inch, 1.1 * inch, 0.85 * inch],
            styles,
        ),
        _pdf_paragraph("6. Findings Summary", styles["section"]),
        _pdf_table(["Severity", "Count"], context["severity_summary"], [2.0 * inch, 1.0 * inch], styles),
        _pdf_paragraph("7. Key Findings", styles["section"]),
        _pdf_table(
            ["Finding title", "Severity", "Check code", "Source records", "Score impact", "Reviewer comment", "Review status"],
            [
                [
                    row.get("title"),
                    row.get("severity"),
                    row.get("check"),
                    row.get("source_record_count"),
                    row.get("score_impact"),
                    row.get("reviewer_comment"),
                    row.get("review_status"),
                ]
                for row in context["key_findings"]
            ],
            [1.6 * inch, 0.65 * inch, 0.75 * inch, 0.65 * inch, 0.65 * inch, 1.45 * inch, 0.8 * inch],
            styles,
        ),
        _pdf_paragraph("8. Recommendations and Required Actions", styles["section"]),
        _pdf_paragraph("System-generated recommendations", styles["table_header"]),
    ]

    for recommendation in context["recommendations"] or ["N/A"]:
        content.append(_pdf_paragraph(f"- {recommendation}", styles["note"]))
    content.append(Spacer(1, 5))
    content.append(_pdf_paragraph("QA required actions", styles["table_header"]))
    for action in context["required_actions"] or ["N/A"]:
        content.append(_pdf_paragraph(f"- {action}", styles["note"]))

    content.extend(
        [
            _pdf_paragraph("9. QA Review / Approval", styles["section"]),
            _pdf_table(
                ["Field", "Value"],
                [
                    ["Current decision/status", context["final_decision"]],
                    ["Submitted by", context["submitted_by"]],
                    ["Submitted date", context["submitted_dt"]],
                    ["Submission notes", context["submission_notes"]],
                    ["QA reviewer / approver", context["decision_by"]],
                    ["QA decision date", context["decision_dt"]],
                    ["QA comments", context["decision_comments"]],
                ],
                [2.1 * inch, 4.8 * inch],
                styles,
            ),
            _pdf_paragraph("10. Electronic Signature", styles["section"]),
            _pdf_table(["Field", "Value"], _signature_rows(context), [2.1 * inch, 4.8 * inch], styles),
            _pdf_paragraph("11. System Notes", styles["section"]),
        ]
    )

    for note in context["config"].system_notes:
        content.append(_pdf_paragraph(f"- {note}", styles["note"]))

    if context["report_status"] == FINAL_REPORT_STATUS and context["signature_records"]:
        content.extend(
            [
                PageBreak(),
                _pdf_paragraph(context["config"].confidentiality_label, styles["controlled"]),
                _pdf_paragraph(context["config"].application_name, styles["app"]),
                _pdf_paragraph("Electronic Signature Page", styles["signature_heading"]),
                _pdf_paragraph(
                    f"Signature Approval for {context['report_version']} {context['report_id']}",
                    styles["status"],
                ),
                Spacer(1, 10),
                _pdf_signature_block_table(context, [2.2 * inch, 4.7 * inch], styles),
            ]
        )

    export_generated_dt = context["export_generated_dt"]
    doc.build(
        content,
        onFirstPage=lambda canvas, document: _draw_footer(canvas, document, export_generated_dt),
        onLaterPages=lambda canvas, document: _draw_footer(canvas, document, export_generated_dt),
    )
    return buffer.getvalue()


async def build_audit_review_report_pdf(db: AsyncSession, report_id: uuid.UUID) -> AuditReviewPdfDownload:
    context = await _load_export_context(
        db,
        report_id,
        allowed_statuses=DOWNLOADABLE_REPORT_STATUSES,
        status_error_message="Only approved audit review reports can be downloaded.",
    )
    report = context["report"]
    stored_pdf_is_current = _stored_pdf_uses_current_template(report)
    if report.report_status == FINAL_REPORT_STATUS and stored_pdf_is_current and (report.final_pdf_path or report.final_pdf_hash):
        final_content = _read_final_pdf_bytes(report)
        if final_content is not None:
            return AuditReviewPdfDownload(
                file_name=context["file_name"],
                media_type=PDF_MEDIA_TYPE,
                content=final_content,
            )
        if report.is_locked:
            raise AuditReviewValidationError(
                "Locked approved report final PDF is unavailable and cannot be regenerated automatically.",
                data={"report_id": str(report.report_id), "final_pdf_path": report.final_pdf_path},
            )

    content = _build_pdf_bytes(context)
    if report.report_status == FINAL_REPORT_STATUS:
        await _persist_final_pdf(
            db,
            report,
            file_name=context["file_name"],
            content=content,
            refresh_template=not stored_pdf_is_current,
        )

    return AuditReviewPdfDownload(
        file_name=context["file_name"],
        media_type=PDF_MEDIA_TYPE,
        content=content,
    )


async def build_audit_review_report_html_preview(db: AsyncSession, report_id: uuid.UUID) -> str:
    context = await _load_export_context(db, report_id)
    return render_audit_review_report_html(context)
